# Generated by Django 4.1.2 on 2022-10-23 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('nome', models.CharField(max_length=50)),
                ('numero', models.IntegerField(max_length=50)),
            ],
        ),
    ]
